version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    environment:
      DB_HOST                    : ${DB_HOST}
      DB_PORT                    : ${DB_PORT}
      DB_USER                    : ${DB_USER}
      DB_PASS                    : ${DB_PASS}
      SECRET_KEY_BASE            : ${SECRET_KEY_BASE}
      FORTYTWO_KEY               : ${FORTYTWO_KEY}
      FORTYTWO_SECRET            : ${FORTYTWO_SECRET}
      SENTRY_DSN                 : ${SENTRY_DSN}
      AOC_LEADERBOARD_ID         : ${AOC_LEADERBOARD_ID}
      AOC_LEADERBOARD_JOIN_TOKEN : ${AOC_LEADERBOARD_JOIN_TOKEN}
      AOC_LOGIN_TOKEN            : ${AOC_LOGIN_TOKEN}

    env_file:
    - "../.env"

    container_name: advent-dev-app

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:15
    container_name: advent-dev-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: advent
      POSTGRES_PASSWORD: ${DB_PASS}
      # Your config/database.yml should use the user and password you set here,
      # and host "db" (as that's the name of this service). You can use whatever
      # database name you want. Use `bin/rails db:prepare` to create the database.
      #
      # Example:
      #
      #  development:
      #    <<: *default
      #    host: db
      #    username: postgres
      #    password: postgres
      #    database: myapp_development

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
