when:
- branch: main
  event: [push, manual]
depends_on:
  - test

steps:
  build-and-publish:
    image: woodpeckerci/plugin-kaniko
    secrets: [FORGE_OCI]
    settings:
      repo: casper-oci/advent_leaderboard
      tag: latest
      registry: forge.vloot.dev
      username: casper
      password:
        from_secret: FORGE_OCI
