when:
- branch: main
  event: [push, manual]

depends_on:
  - test

steps:
  build-and-publish:
    image: woodpeckerci/plugin-kaniko
    settings:
      repo: casper/advent_leaderboard
      tag: latest
      registry: forge.vloot.dev
      username: casper
      password:
        from_secret: FORGE_OCI
